apiVersion: v1
kind: Service
metadata:
  name: notifier-service
  labels:
    app: kafka-cqrs
spec:
  selector:
    app: kafka-cqrs
    service: notifier-service
  ports:
  - name: notifier-service-port
    protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-cqrs-notifier-service
  labels:
    app: kafka-cqrs
    service: notifier-service
spec:
  selector:
    matchLabels:
      app: kafka-cqrs
      service: notifier-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-cqrs
        service: notifier-service
    spec:
      containers:
      - name: notifier-service
        image: jojczykp.pl/kafka-cqrs/notifier-service:0.0.1
        ports:
          - containerPort: 8081
