apiVersion: v1
kind: Service
metadata:
  name: producer-service
  labels:
    app: kafka-cqrs
spec:
  selector:
    app: kafka-cqrs
    service: producer-service
  ports:
  - name: producer-service-port
    protocol: TCP
    port: 8083
    targetPort: 8083
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-cqrs-producer-service
  labels:
    app: kafka-cqrs
    service: producer-service
spec:
  selector:
    matchLabels:
      app: kafka-cqrs
      service: producer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-cqrs
        service: producer-service
    spec:
      containers:
      - name: producer-service
        image: jojczykp.pl/kafka-cqrs/producer-service:0.0.1
        ports:
          - containerPort: 8083
